site_name: Canefinder
site_description: Pathfinder 1e house rules
docs_dir: docs
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes
    - search.highlight
    - search.suggest
    - toc.follow
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/weather-night
        name: Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Light mode
plugins:
  - search
  - awesome-nav
markdown_extensions:
  - tables
  - toc
  - admonition
  - pymdownx.details
extra_css:
  - stylesheets/extra.css
