nav:
  - index.md
  - Armor and Shields: armor.md
  - Specific Armors and Shields: armor-specific.md
  - Weapons: weapons.md
  - Specific Weapons: weapons-specific.md
  - Potions and Oils: potions.md
  - Rings: rings.md
  - Rods: rods.md
  - Scrolls: scrolls.md
  - Wands: wands.md
  - "*"
