nav:
  - how-combat-works.md
  - actions-in-combat.md
  - injury-and-death.md
  - movement-position-and-distance.md
  - big-and-little-creatures-in-combat.md
  - combat-modifiers.md
  - special-attacks.md
  - special-initiative-actions.md
