nav:
  - Home: index.md
  - Rules: rules
  - Characters: characters
  - Magic: magic
  - Equipment: equipment
  - Gamemastering: gamemastering
  - Campaign Systems: campaign-systems
  - About: about.md
